---
abstract: 'a Database-agnostic driven Event Emitter'
author:
  - 'mudler <mudler@dark-lab.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build::Tiny: 0.035
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Deeme
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
recommends:
  feature: 0
requires:
  MIME::Base64: 0
  Scalar::Util: 0
  perl: 5.008_005
resources:
  bugtracker: https://github.com/mudler/p5-Deeme/issues
  homepage: https://github.com/mudler/p5-Deeme
  repository: https://github.com/mudler/p5-Deeme.git
version: 0.03
